DeltaxApplication/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;

namespace DeltaxApplication.Models
{
    public class Movie
    {
        public Movie()
        {
            this.Actors = new HashSet<Actor>();
            this.SelectedActorIds = new List<int>();
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "Movie Name Cannot be empty")]
        public string Name { get; set; }
        public string Plot { get; set; }
        [Required(ErrorMessage = "Year Of Release Cannot be null")]
        public int Year_Of_Release { get; set; }

        public Nullable<int> ProducerId { get; set; }
        public byte[] Poster { get; set; }
        public virtual Producer Producer { get; set; }

        public virtual ICollection<Actor> Actors { get; set; }
        [EnsureOneElement(ErrorMessage = "Atleast One Actor Needed To Be Selected")]
        [NotMapped] public List<int> SelectedActorIds { get; set; }
    }

   
}

DeltaxApplication/Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DeltaxApplication.Models;
using DeltaxApplication.Repository;

namespace DeltaxApplication.Controllers
{
    public class ActorController : Controller
    {
        // GET: Actor
        private ActorRepository _actorRepository;

        public ActorController()
        {
            this._actorRepository = new ActorRepository(new MovieDbContext());

        }
        protected override void Dispose(bool disposing)
        {
            _actorRepository.Dispose();
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Actor x = _actorRepository.GetActor(id);
            return View(x);
        }


        [HttpPost]
        public JsonResult Save(Actor actor)
        {

            _actorRepository.AddActor(actor);
           _actorRepository.SaveChanges();
            return Json(new
            {
                actor
            });
        }



    }
}

DeltaxApplication/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Validation;
using DeltaxApplication.ViewModel;
using System.Web;
using System.Web.Mvc;
using DeltaxApplication.Models;
using DeltaxApplication.Repository;
using Microsoft.Ajax.Utilities;

namespace deltaxapp.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        private MovieRepository _movieRepository;
        private ActorRepository _actorRepository;
        private ProducerRepository _producerRepository;

        public MovieController()
        {
            var context = new MovieDbContext();
            this._movieRepository = new MovieRepository(context);
            this._producerRepository=new ProducerRepository(context);
            this._actorRepository=new ActorRepository(context);

        }
        protected override void Dispose(bool disposing)
        {
            _movieRepository.Dispose();
        }

        public ActionResult Index()

        {
            var movies = _movieRepository.GetMovies();
            return View(movies);
        }
        /* 
       public ActionResult AddImage()
       {
           Movie m = new Movie();
           return View(m);
       }

       [HttpPost]
         public ActionResult AddImage(Movie mov, HttpPostedFileBase image1)
         {
             if (image1 != null)
             {
                 mov.Poster=new byte[image1.ContentLength];
                 image1.InputStream.Read(mov.Poster, 0, image1.ContentLength);
             }

             _context.Movies.Add(mov);
             _context.SaveChanges();
             return View(mov);

         }
 */
        public ActionResult New()
        {
            var producers = _producerRepository.GetProducers();
            var actors = _actorRepository.GetActors();
            var viewModel = new NewMovieViewModel
            {
                Producers = producers,
                Actors= actors
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Movie movie, HttpPostedFileBase image1)
        {
            HashSet<Actor> selectedActors = new HashSet<Actor>();
            if (ModelState.IsValid)
            {
                if (image1 != null)
                {
                    movie.Poster = new byte[image1.ContentLength];
                    image1.InputStream.Read(movie.Poster, 0, image1.ContentLength);
                }







                if (movie.Id == 0)
                {

                    foreach (var x in movie.SelectedActorIds)
                    {
                      //  selectedActors.Add(_context.Actors.SingleOrDefault(i=>i.Id==x));
                        selectedActors.Add(_actorRepository.GetActor(x));
                    }

                    movie.Actors = selectedActors;
                    //   _context.Movies.Add(movies);
                    _movieRepository.AddMovie(movie);
                   
                   // _context.SaveChanges();
                    _movieRepository.SaveChanges();

                    TempData["notice"] = movie.Name + " Added Successfully ";

                }
                else
                {
                   
                    //var movindb = _context.Movies.Include(c => c.Actors).SingleOrDefault(c => c.Id == movies.Id);
                    var movindb = _movieRepository.GetMovie(movie.Id);
                   var existingactorids= movindb.Actors.Select(actor=>actor.Id).ToList();
                    var newactorids = movie.SelectedActorIds.Except(existingactorids);
                    var deletedactorids = existingactorids.Except(movie.SelectedActorIds);
                    
                 //   foreach (var x in movies.SelectedActorIds)
                   // {
                      //  selectedActors.Add(_context.Actors.SingleOrDefault(i=>i.Id==x));
                    //}

                   // movies.Actors = selectedActors;

                    foreach (var x in newactorids)
                    {
                       // var actor = _context.Actors.SingleOrDefault(a => a.Id == x);
                        var actor = _actorRepository.GetActor(x);
                        movindb.Actors.Add(actor);


                    }
                    foreach (var x in deletedactorids)
                    {
                      //  var actor = _context.Actors.SingleOrDefault(a => a.Id == x);
                        var actor = _actorRepository.GetActor(x);
                        movindb.Actors.Remove(actor);


                    }




                    movindb.Name = movie.Name;
                    movindb.Plot = movie.Plot;
                    movindb.Id = movie.Id;
                    movindb.Year_Of_Release = movie.Year_Of_Release;
                   
                    movindb.Poster = movie.Poster;
                    movindb.SelectedActorIds = movie.SelectedActorIds;

                    _movieRepository.SaveChanges();
                    TempData["notice"] = movie.Name + " Edited Successfully ";
                }

                return RedirectToAction("Index", "Movie");
            }
            else
            {
                var producers = _producerRepository.GetProducers();
                var actors = _actorRepository.GetActors();
                var viewModel = new NewMovieViewModel
                {
                    Producers = producers,
                    Actors= actors,
                    Movie = movie

                };

                return View("New", viewModel);
            }
        }


        public ActionResult Edit(int id)
        {
            //var movie = _context.Movies.SingleOrDefault(c => c.Id == id);
            var movie = _movieRepository.GetMovie(id);
            if (movie == null)
            {
                return HttpNotFound();

            }

            movie.SelectedActorIds = movie.Actors.Select(actor => actor.Id).ToList();
            var viewModel = new NewMovieViewModel()
            {

                Producers = _producerRepository.GetProducers(),
                Actors =_actorRepository.GetActors(),
                Movie = movie

            };


            if (movie.Poster != null)
            {
                ViewBag.Image = Convert.ToBase64String(movie.Poster);

            }



            return View("New", viewModel);

        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Movie mov = _movieRepository.GetMovie(id);
            if (mov == null)
            {
                return HttpNotFound();
            }

            _movieRepository.DeleteMovie(mov);
            _movieRepository.SaveChanges();

            TempData["notice"] = mov.Name + " Deleted Successfully ";


            return RedirectToAction("Index", "Movie");

        }


        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Movie movie = _movieRepository.GetMovie(id);
            if (movie == null)
            {
                return HttpNotFound();
            }

            if (movie.Poster != null)
            {
                ViewBag.Image = Convert.ToBase64String(movie.Poster);

            }
            else if (movie.Poster == null)
            {
                ViewBag.Image = null;
            }

            return View(movie);


        }





    }
}

DeltaxApplication/Controllers/ProducerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Net;
using System.Data.Entity.Validation;
using DeltaxApplication.Interfaces;
using DeltaxApplication.Models;
using DeltaxApplication.Repository;
using Microsoft.Ajax.Utilities;

namespace DeltaxApplication.Controllers
{
    public class ProducerController : Controller
    {
        // GET: Producer
        private ProducerRepository _producerRepository;

        public ProducerController()
        {
            this._producerRepository = new ProducerRepository(new MovieDbContext());

        }
        protected override void Dispose(bool disposing)
        {
            _producerRepository.Dispose();
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Producer x = _producerRepository.GetProducer(id);
            return View(x);

        }

        [HttpPost]
        public JsonResult Save(Producer producer)
        {
           
            _producerRepository.AddProducer(producer);
            _producerRepository.SaveChanges();




            return Json(new
            {
                producer
            });
        }


    }
}

DeltaxApplication/Views/Movie/Details.cshtml
@using DeltaxApplication.Models

@model DeltaxApplication.Models.Movie

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details:</h2>

<body>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>



    <h4>
        @Html.DisplayFor(model => model.Name)
    </h4>
    @if (ViewBag.ImageToShow != null)
    {

        @Html.DisplayNameFor(model => model.Poster)


    }
    @*@{
            var base64 = Convert.ToBase64String(Model.Poster);
            var imgsrc = string.Format("data:image/png;base64,", base64);
        }
    *@
    @if (ViewBag.Image != null)
    {
        @Html.Raw("<img id=\"imageid\" src=\"data:image/JPG;base64," + ViewBag.Image + "\" height=\"250\" width=\"250\" />")
    }

    <table class="table table-bordered ">

        <tr>
            <th>
                Plot
            </th>

            <td>
                @Html.DisplayFor(model => model.Plot)
            </td>
        </tr>
        <tr>
            <th>
                YEAR OF RELEASE
            </th>

            <td>
                @Html.DisplayFor(model => model.Year_Of_Release)
            </td>
        </tr>
        <tr>
            <th>
                Producer
            </th>

            <td>
                @Html.ActionLink(Model.Producer.Name, "Details", "Producer", new { id = Model.Id }, null)
            </td>
        </tr>
        <tr>
            <th>Actors</th>
            <td>
                @foreach (var x in Model.Actors)
                {
                    @Html.ActionLink(x.Name, "Details", "Actor", new { id = x.Id }, null)

                    <br />

                }
            </td>
        </tr>

    </table>
</body>

DeltaxApplication/Views/Movie/Index.cshtml
@using DeltaxApplication.Models
@model IEnumerable<DeltaxApplication.Models.Movie>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}





<body>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript">
        function DeleteConfirm() {

            if (confirm("Are you sure want to delete record"))
                return true;
            else
                return false;
        }
    </script>

    @if (TempData["notice"] != null)
    {


        <div class="alert alert-warning">

            <strong>@TempData["notice"]</strong>
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        </div>


    }



    <table class="table table-bordered table-hover">
        <tr>
            <th>
                Name
            </th>
            @*  <th>
                    PLOT
                </th>*@
            <th>
                YEAR OF RELEASE
            </th>
            <th>

                Producer
            </th>
            <th>
                Actors
            </th>
            <th></th>
        </tr>

        @foreach (var mov in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(mov.Name, "Details", "Movie", new { id = mov.Id }, null)


                </td>
                @* <td>
                        @Html.DisplayFor(modelItem => mov.Plot)
                    </td>*@
                <td>
                    @mov.Year_Of_Release
                </td>
                <td>
                    @Html.ActionLink(mov.Producer.Name, "Details", "Producer", new { id = mov.ProducerId }, null)


                </td>
                <td>
                    @foreach (var x in mov.Actors)
                    {
                        @Html.ActionLink(x.Name, "Details", "Actor", new { id = x.Id }, null)



                        <br />
                    }
                </td>
                <td>
                    @Html.ActionLink("edit", "Edit", "Movie", new { id = mov.Id }, null)
                    <br />



                    @Html.ActionLink("Delete", "Delete", "Movie", new { id = mov.Id }, new { onclick = " return DeleteConfirm()" })
                </td>








            </tr>
        }

    </table>



</body>

DeltaxApplication/Views/Movie/New.cshtml
@using DeltaxApplication.Models
@model DeltaxApplication.ViewModel.NewMovieViewModel
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/chosen.css" rel="stylesheet" />

@Scripts.Render("~/bundles/movies")
@Styles.Render("~/Content/new")

<style>
    .input-validation-error {
        border: 1px solid red;
    }
</style>










@using (Html.BeginForm("Create", "Movie", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">

        @if (ViewBag.Image != null)
        {
            @Html.Raw("<img id=\"imageid\" src=\"data:image/JPG;base64," + ViewBag.Image + "\"    height=\"180\" width=\"100\"/>")
        }


        <br />

        @Html.LabelFor(n => n.Movie.Name)
        @Html.TextBoxFor(n => n.Movie.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(n => n.Movie.Name)
        @if (Model.Movie != null)
        {
            @Html.HiddenFor(n => n.Movie.Id, new { @class = "form-control" })
        }
    </div>
    <div class="form-group">
        @Html.LabelFor(n => n.Movie.Plot)
        @Html.TextBoxFor(n => n.Movie.Plot, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Producer</label>
        <br />
        @*  @Html.LabelFor(n => n.movies.Producer.Name)*@
        @Html.DropDownListFor(n => n.Movie.ProducerId, new SelectList(Model.Producers, "Id", "Name"), new { @class = "form-control", id = "producerddl", style = "width: 300px;" })

        <button type="button" id="prodid">Add Producer</button>
    </div>

    <div class="form-group">
        @Html.LabelFor(n => n.Movie.Year_Of_Release)
        @Html.TextBoxFor(n => n.Movie.Year_Of_Release, new { @class = "form-control" })

        @Html.ValidationMessageFor(n => n.Movie.Year_Of_Release)
    </div>
    <div class="form-group">


        @Html.LabelFor(n => n.Movie.Actors)
        <br />
        @Html.ListBoxFor(n => n.Movie.SelectedActorIds, new MultiSelectList(Model.Actors, "Id", "Name"), new { multiple = "multiple", id = "actorddl", style = "width: 600px;" })

        @Html.HiddenFor(m => m.Movie.Poster, new { @class = "form-control" })


        <button type="button" id="actid">Add Actor</button>


        <br />
        @Html.ValidationMessageFor(n => n.Movie.SelectedActorIds)
        <br />
    </div>
    <div class="col-md-10">

        <input type="file" id="image1" name="image1" size="25" />

    </div>
    <br />
    <br />
    <button type="submit" class="btn btn-primary">Save</button>


    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog ">




            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Create Actor</h4>
                </div>
                <div class="modal-body" id="modal-body">
                    <form id="actorform">
                        Name: <input type="text" name="Name" id="actornameid" />
                        <label id="actorlabel"></label><br />
                        Sex: <input type="radio" name="gender" value="Male" id="actormaleid" checked> Male
                        <input type="radio" name="gender" value="Female" id="actorfemaleid"> Female
                        <input type="radio" name="gender" value="Other" id="actorotherid"> Other <br />
                        DateofBirth:
                        <input type="date" name="bday" id="actorbdayid">
                        <br />
                        Bio<br />
                        <textarea rows="4" cols="50" id="actorbioid">

                            </textarea>

                    </form>
                    <div class="loader col-md-offset-4"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-primary" id="actorbuttonid">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>

            </div>

        </div>
    </div>

    





    <div class="modal fade" id="myModalproducer" role="dialog">
        <div class="modal-dialog ">




            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Create Producer</h4>
                </div>
                <div class="modal-body" id="modal-body">
                    <form id="producerform">

                        Name: <input type="text" class="form-control " name="producernameid" id="producernameid" /> <br />
                        Sex: <input type="radio" name="gen" value="Male" id="producermaleid" checked> Male
                        <input type="radio" name="gen" value="Female" id="producerfemaleid"> Female
                        <input type="radio" name="gen" value="Other" id="producerotherid"> Other <br />
                        DateofBirth:
                        <input type="date" name="bday" id="producerbdayid">
                        <br />
                        Bio<br />
                        <textarea rows="4" cols="50" id="producerbioid">

                            </textarea>


                        <div class="loader col-md-offset-4"></div>

                        <div class="modal-footer">
                            <button type="button" class="btn-primary" id="producerbuttonid">Save</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
   


   
}